export const LOAD_ALL_PROVINCES_DATA = "LOAD_ALL_PROVINCES_DATA";
export const LOAD_CANADA_DATA = "LOAD_CANADA_DATA";
export const SET_CASE_TYPE = "SET_CASE_TYPE";
export const SET_PROVINCE_INPUT = "SET_PROVINCE_INPUT";
export const LOAD_HISTORICAL_CANADA = "LOAD_HISTORICAL_CANADA";
export const SET_TYPE_INPUT = "SET_TYPE_INPUT";
export const LOAD_HISTORICAL_PROVINCES = "LOAD_HISTORICAL_PROVINCES";
export const LOAD_MAP = 'LOAD_MAP';